[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.10.0"
rust-i18n = "1"
regex = "1"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.9.21"
current_locale="0.1.1"
tui = "0.19"
crossterm = "0.25"
rand = "0.8.3"
perlin2d = "0.2.6"
