[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
current_locale="0.1.1"
locales="0.1.0"
tui = "0.19"
crossterm = "0.25"
rand = "0.8.3"
perlin2d = "0.2.6"
